apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
     argocd.argoproj.io/manifest-generate-paths: "/sample3"
spec:
  project: default
  source:
    repoURL: https://github.com/hamedbrd/argocd-example-apps
    targetRevision: test-argocd-stuff
    path: sample3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.

